- name: Ensure Git is Installed
  yum:
    name: git
    state: present

- name: Check if awx Repo is already cloned
  become: no
  stat:
    path: "{{ netbox_repo_dir }}"
  register: netbox_repo_exists

- name: Clone Netbox into configured directory.
  become: no
  git:
    repo: "{{ netbox_repo }}"
    dest: "{{ netbox_repo_dir }}"
    version: "{{ netbox_docker_version }}"
    force: true
    accept_hostkey: true
  when: not netbox_repo_exists.stat.exists

- name: Pull Docker Images
  tags: install
  become: no
  command: /usr/local/bin/docker-compose pull
  args:
    chdir: "{{ netbox_repo_dir }}"
  environment:
    VERSION: "{{ netbox_version }}"

# - name: Copy docker-compose override
#   become: no
#   copy:
#     src: "{{ netbox_repo_dir }}/docker-compose.override.yml.example"
#     dest: "{{ netbox_repo_dir }}/docker-compose.override.yml"
#     remote_src: yes

# - name: Adjust Port for Netbox
#   become: no
#   replace:
#     path: '{{ netbox_repo_dir }}/docker-compose.override.yml'
#     regexp: '8000:8080'
#     replace: '80:8080'


- name: Start All Containers
  tags: install
  become: no
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ netbox_repo_dir }}"
  environment:
    VERSION: "{{ netbox_version }}"

# - name: Open Ports for Netbox
#   import_role:
#     name: infra/open_firewall
#   vars:
#     port: '80/tcp'
